<a href="https://colab.research.google.com/github/pecey/PythonTutorials/blob/master/Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Hello World

In [0]:
print("Hello World")

Hello World


## Variables

In [0]:
# String
a = "Hello World"

# Integers
b = 4

# Decimals
c = 3.14

# Print all the variables separated by space
print(a,b,c)

Hello World 4 3.14


### Strings

String is one of the most common used data type in Python. You create a string by enclosing some characters or numbers in single (') or double (") quotes.

In [0]:
first_string = "Hello"
second_string = "World"

# String concatenation
print(first_string + second_string)

HelloWorld


In [0]:
# Adding a space in between words
print(first_string + " " + second_string)

Hello World


In [0]:
# Better way to add spaces. Or create a string in general
print("{} {}".format(first_string, second_string))

Hello World


In [0]:
#Interconversion
x = 20
print(type(x))
xf = float(x)
print(type(xf))
xs = str(x)
print(type(xs))

<class 'int'>
<class 'float'>
<class 'str'>


In [0]:
print(" The integer is "+ str(x) + ", the float is "+str(xf)+ " and the string is "+str(xs))

 The integer is 20, the float is 20.0 and the string is 20


## Data Structures

More here: https://docs.python.org/3/tutorial/datastructures.html

- List
- Set
- Dictionary

### List

In [0]:
# Create an empty list
empty_list = list()
empty_list_2 = []

# Initialise a list with a few elements.
# Unlike other languages, can hold data of any type.
my_list = ["Hello", "World", 4, 3.14, []]

In [0]:
# Retrieve data from list using index
print(my_list[2])

4


#### Methods on list

In [0]:
# Add an element to the end of the list
my_list.append(9)
print(my_list)

['Hello', 'World', 4, 3.14, [], 9]


In [0]:
# Add multiple elements at once to the back of the list. 
# Notice that although the parameter to extend is a list, it adds the elements individually
my_list.extend([10,11])
print(my_list)

['Hello', 'World', 4, 3.14, [], 9, 10, 11]


In [0]:
# Insert element at a specific index of the list
my_list.insert(1, "Everyone")
print(my_list)

['Hello', 'Everyone', 'World', 4, 3.14, [], 9, 10, 11]


In [0]:
# Remove the first occurance of a given element
my_list.append(10)
print("Before removal {}".format(my_list))
my_list.remove(10)  
print("After removal {}".format(my_list))

Before removal ['Hello', 'Everyone', 'World', 4, 3.14, [], 9, 10, 11, 10]
After removal ['Hello', 'Everyone', 'World', 4, 3.14, [], 9, 11, 10]


In [0]:
# Remove the last element from the list. If index is passed, then remove the particular element from list
temp = my_list.pop()
print(temp)
print(my_list)

temp = my_list.pop(2)
print(temp)
print(my_list)

10
['Hello', 'Everyone', 'World', 4, 3.14, [], 9, 11]
World
['Hello', 'Everyone', 4, 3.14, [], 9, 11]


In [0]:
# Sort a list
unsorted_list = [1,2,87,3,56,391,32,46,0, -1]
sorted_list = unsorted_list.sort()
#unsorted_list
sorted_list

In [0]:
# Reverse a list
print(my_list)
my_list.reverse()
print(my_list)

['Hello', 'Everyone', 4, 3.14, [], 9, 11]
[11, 9, [], 3.14, 4, 'Everyone', 'Hello']


### Set

> A set is an **unordered** collection with no duplicate elements. Set objects also support mathematical operations like union, intersection, difference, and symmetric difference.

> Mutable — the contents can be changed using methods like add() and remove()

More : https://docs.python.org/3/library/stdtypes.html#set

In [0]:
empty_set = set()
empty_set.add("Element")
print(empty_set)

{'Element'}


In [0]:
basket = {'apple', 'orange', 'apple', 'pear', 'orange', 'banana'}
print(basket)

{'pear', 'apple', 'banana', 'orange'}


In [0]:
# Checking the set for presence or absence
print("orange" in basket)
print("carrot" in basket)

True
False


### Dictionary

> It is best to think of a dictionary as a set of *key: value* pairs, with the requirement that the keys are unique (within one dictionary).

> Dictionaries are indexed by keys, which can be any **immutable** type; strings and numbers can always be keys. Tuples can be used as keys if they contain only strings, numbers, or tuples; if a tuple contains any mutable object either directly or indirectly, it cannot be used as a key. You can’t use lists as keys

In [0]:
tel = {'jack': 4098, 'harry': 4139}
tel['ron'] = 4127

print(tel)

{'jack': 4098, 'harry': 4139, 'ron': 4127}


In [0]:
# Overwrite an existing key
tel['ron'] = 5000
print(tel)

{'jack': 4098, 'harry': 4139, 'ron': 5000}


In [0]:
# Check if present
print("ron" in tel)

# Checks only on keys
print(5000 in tel)

True
False


In [0]:
# Get keys of dictionary
print(list(tel))

# Notice the type. Returns an object of dict_keys
print(tel.keys())

['jack', 'harry', 'ron']
dict_keys(['jack', 'harry', 'ron'])


## Loops

There are two types of loops in Python.
- for
- while.

For loops iterate over a given sequence. Here is an example:

In [0]:
# Iterate over a list
primes = [2, 3, 5, 7]
for prime in primes:
    print(prime)

2
3
5
7


In [0]:
# Iterate over a range of numbers
# Notice : last number in range is always excluded
for num in range(0,10,1):
    print(num)

0
1
2
3
4
5
6
7
8
9


In [0]:
# Iterate over the words as well as index of the word
words = ["Hello", "World", "Python", "is", "awesome"]
for index, word in enumerate(words):
    print("Index {}: Word {}".format(index, word))

Index 0: Word Hello
Index 1: Word World
Index 2: Word Python
Index 3: Word is
Index 4: Word awesome


### Lambdas

> Python supports the creation of anonymous functions (i.e. functions that are not bound to a name) at runtime, using a construct called "lambda". They are often used in conjunction with typical functional concepts like filter(), map() and reduce()

In [0]:
def f (x): return x**2
print(f(8))

64


In [0]:
g = lambda x: x**2
print(g(8))

64


The advantage of a lambda is not evident from this example. It would be better understood when used in conjunction of concepts like filter(), map() and reduce() 

### Map

> Applying an operation to each item of a list or sequence and collect the result. 

In [0]:
numbers = list(range(0,10))
print(numbers)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [0]:
# Square numbers : Using a for loop
squared_numbers = []
for number in numbers:
    squared_numbers.append(number ** 2)
print(squared_numbers)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [0]:
# Square numbers : Using a map
def square_num(x):
    return x**2

print(list(map(square_num, numbers)))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [0]:
# Square numbers : Using a map with lambda
print(list(map(lambda x: x**2, numbers)))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


### Filter

> Filters out items based on a test function which is a filter

In [0]:
numbers = list(range(0,10))
print(numbers)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [0]:
# Find odd numbers : Using a for loop
odd_numbers = []
for num in numbers:
    if num%2 == 1:
        odd_numbers.append(num)
        
print(odd_numbers)

[1, 3, 5, 7, 9]


In [0]:
# Filter out even numbers. Removes the elements that match the filter.
print(list(filter(lambda x: x%2, numbers)))

[1, 3, 5, 7, 9]


### Reduce

>  This function reduces a list to a single value by combining elements via a supplied function

In [0]:
numbers = list(range(0,10))

# Adding numbers: Using for loop
total = 0
for num in numbers:
    total = total + num

print(total)

45


In [0]:
# Adding numbers: Using reduce

from functools import reduce
reduce((lambda x,y: x+y), numbers)

45

In [0]:
# Bad example - can call the sum() method on list
sum(numbers)

45

### Itertools

The functions provided are inspired by similar features of “lazy functional programming languages”. 

**Why iterators?**  
Iterator-based code may be preferred over code which uses lists for several reasons. Since data is not produced from the iterator until it is needed, all of the data is not stored in memory at the same time. 

In [0]:
first_list = [1,2,3]
second_list = ['a','b','c']

# Need a function that iterates over the concatenation of both the lists
# Simple way

third_list = first_list + second_list
for i in third_list:
  print(i)



1
2
3
a
b
c


In [0]:
# Disadvantage of the previous approach: Now you have first_list, second_list and third_list in memory. third_list is essentially redundant since it is just a concatenation of first_list and second_list. Instead create an iterator.
from itertools import *
chained_list = chain(first_list, second_list)

# chaining together multiple iterables
for i in chain(chained_list):
  print(i)


1
2
3
a
b
c


In [0]:
#!pip install pympler
from pympler.asizeof import asizeof

print(asizeof(third_list))
print(asizeof(chained_list))

400
56


In [0]:
# Groupby

data = [("key1", "value1"), ("key1", "value2"), ("key2", "value3"), ("key3", "value4"), ("key3", "value5")]
for key, values in groupby(data, lambda x: x[0]):
    print(key, list(values))

key1 [('key1', 'value1'), ('key1', 'value2')]
key2 [('key2', 'value3')]
key3 [('key3', 'value4'), ('key3', 'value5')]


In [0]:
# Permutations

sample = ["A","B","C"]
list(permutations(sample, 2))

[('A', 'B'), ('A', 'C'), ('B', 'A'), ('B', 'C'), ('C', 'A'), ('C', 'B')]

In [0]:
# Combinations

sample = ["A","B","C"]
list(combinations(sample,2))

[('A', 'B'), ('A', 'C'), ('B', 'C')]

### List Comprehensions

List Comprehensions provide an elegant way to create new lists. The following is the basic structure of a list comprehension:

output_list = [output_exp for var in input_list if (var satisfies this condition)]

Note that list comprehension may or may not contain an if condition. List comprehensions can contain multiple for (nested list comprehensions).



In [0]:
# Usual way of writing a for loop

numbers = [1, 2, 3, 4, 5]
squares = []

for n in numbers:
  squares.append(n**2)

print(squares) 

[1, 4, 9, 16, 25]


In [0]:
# Using List comprehensions

numbers = [1, 2, 3, 4, 5]
squares = [n**2 for n in numbers]

print(squares) 

[1, 4, 9, 16, 25]


**Using if condition in List Comprehension**

In [0]:
#Suppose we want to create an output list which contains only the even numbers which are present in the input list. 
#Let’s see how to do this using for loops and list comprehension and decide which method suits better.

# Constructing output list WITHOUT 
# Using List comprehensions 
input_list = [1, 2, 3, 4, 4, 5, 6, 7, 7] 
  
output_list = [] 
  
# Using loop for constructing output list 
for var in input_list: 
    if var % 2 == 0: 
        output_list.append(var) 
  
print("Output List using for loop:", output_list) 

Output List using for loop: [2, 4, 4, 6]


In [0]:
# Using List comprehensions 
# for constructing output list 
  
input_list = [1, 2, 3, 4, 4, 5, 6, 7, 7] 
  
  
list_using_comp = [var for var in input_list if var % 2 == 0] 
  
print("Output List using list comprehensions:", 
                               list_using_comp) 

Output List using list comprehensions: [2, 4, 4, 6]


**Using multiple for loops in List Comprehensions**

In [0]:
# Find common numbers from two list using list comprehension:

# Without List comprehension

list_a = [1, 2, 3, 4]
list_b = [2, 3, 4, 5]

common_num = []

for a in list_a:
  for b in list_b:
    if a == b:
      common_num.append(a)
      
print(common_num)

[2, 3, 4]


In [0]:
# With List comprehension

list_a = [1, 2, 3, 4]
list_b = [2, 3, 4, 5]

common_num = [a for a in list_a for b in list_b if a == b]

print(common_num)

[2, 3, 4]


### Dictionary Comprehensions

Extending the idea of list comprehensions, we can also create a dictionary using dictionary comprehensions. The basic structure of a dictionary comprehension looks like below.

output_dict = {key:value for (key, value) in iterable if (key, value satisfy this condition)}

In [0]:
# Suppose we want to create an output dictionary which contains only the odd numbers that are present in the input list as keys and their 
# cubes as values. Let’s see how to do this using for loops and dictionary comprehension.

# Without Dictionary Comprehension

input_list = [1, 2, 3, 4, 5, 6, 7] 
  
output_dict = {} 
  
# Using loop for constructing output dictionary 
for var in input_list: 
    if var % 2 != 0: 
        output_dict[var] = var**3
  
print("Output Dictionary using for loop:", 
                             output_dict )

Output Dictionary using for loop: {1: 1, 3: 27, 5: 125, 7: 343}


In [0]:
# Using Dictionary Comprehension

input_list = [1,2,3,4,5,6,7] 
  
dict_using_comp = {var:var ** 3 for var in input_list if var % 2 != 0} 
  
print("Output Dictionary using dictionary comprehensions:", 
                                           dict_using_comp)

Output Dictionary using dictionary comprehensions: {1: 1, 3: 27, 5: 125, 7: 343}


In [0]:
# Given two lists containing the names of states and their corresponding capitals, construct a dictionary which maps the states 
# with their respective capitals. Let’s see how to do this using for loops and dictionary comprehension.

# Without using Dictionary comprehension

state = ['Gujarat', 'Maharashtra', 'Rajasthan'] 
capital = ['Gandhinagar', 'Mumbai', 'Jaipur'] 
  
output_dict = {} 
  
# Using loop for constructing output dictionary 
for (key, value) in zip(state, capital): 
    output_dict[key] = value 
  
print("Output Dictionary using for loop:", 
                              output_dict) 

Output Dictionary using for loop: {'Gujarat': 'Gandhinagar', 'Maharashtra': 'Mumbai', 'Rajasthan': 'Jaipur'}


In [0]:
# Using Dictionary Comprehension

state = ['Gujarat', 'Maharashtra', 'Rajasthan'] 
capital = ['Gandhinagar', 'Mumbai', 'Jaipur'] 
  
dict_using_comp = {key:value for (key, value) in zip(state, capital)} 
  
print("Output Dictionary using dictionary comprehensions:",  
                                           dict_using_comp)

Output Dictionary using dictionary comprehensions: {'Gujarat': 'Gandhinagar', 'Maharashtra': 'Mumbai', 'Rajasthan': 'Jaipur'}


## Time

In [0]:
import time
print(time.time())

1572897376.7862399


In [0]:
#Using simple python list
t_start = time.time()

###Enclose any task here to measure its execution time
#time.sleep(5)

t_end = time.time()
print("The time taken is "+str(t_end-t_start))

3.838539123535156e-05


## Numpy

### How do we make a list/array of 10^8 zeroes

In [0]:
list_size = pow(10,8) # or list_size = 10**8
print(list_size)

100000000


In [0]:
#Using simple python list
t_start = time.time()
z_l = []
for i in range(0,list_size):
  z_l.append(0)
t_end = time.time()
print("The time taken is "+str(t_end-t_start))

The time taken is 11.238399505615234


In [0]:
#Using list comprehensions
t_start = time.time()
z_lc = []
z_lc = [0 for i in range(0,list_size)]
t_end = time.time()
print("The time taken is "+str(t_end-t_start))

The time taken is 5.852916479110718


In [0]:
import numpy as np


#Using numpy
t_start = time.time()
z_np = np.zeros((list_size))
t_end = time.time()
print("The time taken is "+str(t_end-t_start))

The time taken is 0.21720027923583984


In [0]:
type(z_lc)

list

In [0]:
#Adding 2 to each element of z
t_start = time.time()

#z_lc = [(i+2) for i in z_lc]
#z_np = z_np + 2

t_end = time.time()
print("The time taken is "+str(t_end-t_start))

The time taken is 4.291534423828125e-05


In [0]:
#Squaring function
t_start = time.time()

z2 = [square_num(i) for i in z_lc]

t_end = time.time()
print("The time taken is "+str(t_end-t_start))

The time taken is 30.371249675750732


In [0]:
#Squaring function
t_start = time.time()

z2_np = square_num(z_np)

t_end = time.time()
print("The time taken is "+str(t_end-t_start))


The time taken is 0.26033449172973633


### To conclude, the more FOR loops your code has the more inefficient it is. Numpy makes use of your multi-core CPU while also making the syntax much more intuitive.

### OPTIONAL

In [0]:
import torch
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
z_t = torch.tensor(z_np).to(device)

The time taken is 0.03542637825012207


In [0]:
t_start = time.time()

z2_t = square_num(z_t)

t_end = time.time()
print("The time taken is "+str(t_end-t_start))

### Commonly used Numpy functions

In [0]:
a = np.zeros((2,2))   # Create an array of all zeros - similarly we also have np.ones,np.eye(feel free to explore)
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"



c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                    

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.40080565 0.26830702]
 [0.91699835 0.33672928]]


In [0]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


In [0]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.int64)
y = y.astype(np.float64)


# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))


# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [0]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


# References


*   http://cs231n.github.io/python-numpy-tutorial/
*   

